### ISSUE TITLE
Should Piece contain information on color?

### ISSUE THREAD

**Issue by dkadillak** [cs414glaad/cs414-f18-001-the-other-alex#31]
After looking at the isMoveValid method in the Piece class and tracing it down, I see that we aren't checking if the piece in toCell is different from the piece in fromCell. How are we going to make sure that if isMoveValid is called on 2 black pieces in legal capturing position that this method wont return true?

tldr: how do we turn friendly fire off?

**Comment by lkwilson** [comment]
For record, we're going to add this check to the move function in Board
